week2/grails-app/domain/week2/User.groovy
package week2

class User {
    String login
    String name
    String surname
    Date   dateCreated
    Date   lastUpdated

    static constraints = {
        login       maxSize: 64, unique: true, index: true
        name        nullable: true
        surname     nullable: true
        lastUpdated nullable: true
    }
}

week2/grails-app/controllers/week2/UserController.groovy
package week2


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

/**
 * UserController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
@Transactional(readOnly = true)
class UserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

	def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    def create() {
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'userInstance.label', default: 'User'), userInstance.login])
                redirect action:"index", method:"GET"
            }
            '*' { respond userInstance, [status: CREATED] }
        }
    }

    def edit(User userInstance) {
        respond userInstance
    }

    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.login])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.login])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'userInstance.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

week2/grails-app/views/layouts/foundation.gsp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><g:layoutTitle default="Grails"/></title>
    <r:require module="modernizr"/>
    <r:require modules="foundation"/>
    <g:layoutHead/>
    <r:layoutResources/>
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'application.css')}" type="text/css">
    <g:javascript library="application"/>
    <!-- workaround buggy plugin in dev mode -->
    <script type="text/javascript" src="/week2/static/js/foundation.js"></script>
</head>
<body>
    <div class="row">
        <div id="spinner" class="spinner" ><g:message code="spinner.alt" default="Loading&hellip;"/></div>
        <g:layoutBody/>
     </div>
    <r:layoutResources/>
    <script type="text/javascript">
        $(document).foundation();
    </script>
</body>
</html>

week2/grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
		<g:javascript library="application"/>		
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<r:layoutResources />
	</body>
</html>

week2/grails-app/views/user/_form.gsp
<%@ page import="week2.User" %>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="user.name.label" default="Name" />
	</label>
	<g:textField name="name" value="${userInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'surname', 'error')} ">
	<label for="surname">
		<g:message code="user.surname.label" default="Surname" />
	</label>
	<g:textField name="surname" value="${userInstance?.surname}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'login', 'error')} ">
    <label for="login">
        <g:message code="user.login.label" default="Login" />
    </label>
    <g:textField name="login" maxlength="64" value="${userInstance?.login}"/>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#name").focus();
        $app.update_login($("#name"), $("#surname"), $("#login"));
    })
</script>

week2/grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="foundation">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="left">
                    <li><g:link action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                </ul>
            </section>
		</nav>
		<div id="create-user" class="content scaffold-create" role="main">
			<h3><g:message code="default.create.label" args="[entityName]" /></h3>
			<g:if test="${flash.message}">
    			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors alert-box alert round" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
                <g:submitButton name="create" class="button small radius" value="${message(code: 'default.button.create.label', default: 'Create')}" />
			</g:form>
		</div>
    </body>
</html>

week2/grails-app/views/user/edit.gsp
<%@ page import="week2.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="foundation">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="left">
                    <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </ul>
            </section>
        </nav>
		<div id="edit-user" class="content scaffold-edit" role="main">
			<h3><g:message code="default.edit.label" args="[entityName]" /></h3>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${userInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
                <g:actionSubmit class="button small radius" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
			</g:form>
		</div>
	</body>
</html>

week2/grails-app/views/user/index.gsp
<%@ page import="week2.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="foundation">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="left">
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </ul>
            </section>
        </nav>
		<div id="list-user" class="content scaffold-list" role="main">
			<h3><g:message code="default.list.label" args="[entityName]" /></h3>
			<g:if test="${flash.message}">
				<div class="alert-box success round" role="status">${flash.message}</div>
			</g:if>
            <g:form url="[resource:userInstance, action:'delete']" method="DELETE">
                <table>
                    <thead>
                        <tr>

                            <g:sortableColumn property="login" title="${message(code: 'user.login.label', default: 'Login')}" />

                            <g:sortableColumn property="name" title="${message(code: 'user.name.label', default: 'Name')}" />

                            <g:sortableColumn property="surname" title="${message(code: 'user.surname.label', default: 'Surname')}" />

                            <g:sortableColumn property="dateCreated" title="${message(code: 'user.dateCreated.label', default: 'Date Created')}" />

                        </tr>
                    </thead>
    				<tbody>
                        <g:each in="${userInstanceList}" status="i" var="userInstance">
                            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                                <td><g:link action="show" id="${userInstance.id}">${fieldValue(bean: userInstance, field: "login")}</g:link></td>

                                <td>${fieldValue(bean: userInstance, field: "name")}</td>

                                <td>${fieldValue(bean: userInstance, field: "surname")}</td>

                                <td><g:formatDate date="${userInstance.dateCreated}" /></td>

                                <td><g:radio name="id" value="${userInstance.id}"/></td>

                            </tr>
                        </g:each>
                    </tbody>
    			</table>
                <div class="pagination">
                    <g:paginate total="${userInstanceCount ?: 0}" />
                </div>
                <g:actionSubmit class="button tiny alert radius" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </g:form>
		</div>
	</body>
</html>

week2/grails-app/views/user/show.gsp
<%@ page import="week2.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="foundation">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
            </ul>
            <section class="top-bar-section">
                <ul class="left">
                    <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </ul>
            </section>
        </nav>
		<div id="show-user" class="content scaffold-show" role="main">
			<h3><g:message code="default.show.label" args="[entityName]" /></h3>
			<g:if test="${flash.message}">
			    <div class="message" role="status">${flash.message}</div>
			</g:if>

			<ol class="property-list user">

				<g:if test="${userInstance?.name}">
				<li class="fieldcontain">
                    <span class="property-value"><g:fieldValue bean="${userInstance}" field="name"/></span>
				</li>
				</g:if>

				<g:if test="${userInstance?.surname}">
				<li class="fieldcontain">
                    <span class="property-value"><g:fieldValue bean="${userInstance}" field="surname"/></span>
				</li>
				</g:if>

                <g:if test="${userInstance?.login}">
                    <li class="fieldcontain">

                        <span class="property-value" aria-labelledby="login-label"><g:fieldValue bean="${userInstance}" field="login"/></span>
                        <span id="login-label" class="label radius"><g:message code="user.login.label" default="Login" /></span>

                    </li>
                </g:if>

				<g:if test="${userInstance?.dateCreated}">
				<li class="fieldcontain">
                    <span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${userInstance?.dateCreated}" /></span>
				</li>
				</g:if>

			</ol>
			<g:form url="[resource:userInstance, action:'delete']" method="DELETE">
                <g:link class="edit" action="edit" resource="${userInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>&nbsp;
                <g:actionSubmit class="button tiny alert radius" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
			</g:form>
		</div>
	</body>
</html>